# example_config.yaml

input_file: "/full/path/to/input_file"
tree_name: "tree_name"
output_dir: "/full/path/to/output_directory"

# Detector settings
detector: ""
fit_ids:
  detector1: 6
  detector2: 7

# New columns to define
new_columns:
  - name: "EXAMPLE_COLUMN"
    expression: "example.dst.variable[{example_index}]"
    init: True

  - name: "ANOTHER_EXAMPLE_COLUMN"
    expression: "another_example.dst.variable[{another_index}][0]"
    init: False # Don't create the column at runtime. It will be calculated on the fly.

# Event Selection Criteria
cuts:
  - "EXAMPLE_COLUMN > 500"
  - "ANOTHER_EXAMPLE_COLUMN < TMath::Pi()"
  - "YET_ANOTHER_EXAMPLE > 4/3"


# Histogram parameters
hist_params:
  # Create a histogram:
  - name: "histogramExample"
    title: "Example Histogram"
    style: "histogram"
    column: "EXAMPLE_COLUMN"
    bins: # Number of bins
    min: # min value
    max: # max value
    x_title: "X label with [units]"
    y_title: "Y label with [units]"
    show_stats: True  # display the stats box
    options: ~

  # Create a profile plot:
  - name: "profileExample"
    title: "Profile Plot Title"
    style: "profile_plot"
    x_column: "EXAMPLE_COLUMN"
    y_column: "ANOTHER_EXAMPLE_COLUMN"
    x_bins: # Number of bins for x-axis
    y_bins: # Number of bins for y-axis
    x_min: # min x value
    x_max: # max x value
    x_bin_edges: # List of bin edges for x-axis. Overrides x_bins, x_min, and x_max.
      - 18.5
      - 18.75
      - 19.0
      - 19.25
      - 19.8
      - 20.3
    y_min:   # min y value
    y_max:   # max y value
    x_title: "X label with [units]"
    y_title: "Y label with [units]"
    show_stats: True  # display the stats box
    options: ""

# For methods defined in the UserFunctions class:
user_functions:
  - name: "Example Function"
    callable: "name_of_method"
    args:
      - name: "column1"
        value: "EXAMPLE_COLUMN"
      - name: "column2"
        value: "ANOTHER_EXAMPLE_COLUMN"
