# txhybid_config.yaml

input_file: ${ALL_HYBRID}
tree_name: "taTree"
output_dir: "/home/zane/software/new_analysis/txHybridDF/results"

# Detector settings
detector: "mdtax4"
detectors:
  - name: "mdtax4"
    site_id: 7
    profile: 6
  - name: "brtax4"
    site_id: 8
    profile: 7

# New columns to define
new_columns:
  - name: "Xmax"
    expression: "prfc.xm[{profile_fit_index}]"
    init: True

  - name: "Xlow"
    expression: "prfc.dep[{profile_fit_index}][0]"
    init: True

  - name: "Xhigh"
    expression: "prfc.dep[{profile_fit_index}][prfc.nbin[{profile_fit_index}]-1]"
    init: True

  - name: "LogEnergy"
    expression: "18. + TMath::Log10(prfc.eng[{profile_fit_index}])"
    init: True

  - name: "Zenith"
    expression: "TMath::RadToDeg()*hctim.mthe[{profile_fit_index}]"
    init: True

  - name: "Psi"
    expression: "TMath::RadToDeg()*hctim.mpsi[{profile_fit_index}]"
    init: True

  - name: "PulseArea"
    expression: "tlfptn.pulsa"
    init: True

  - name: "TriggeredSDCount"
    expression: "tlfptn.nhits"
    init: True

  - name: "GeometryFitStatus"
    expression: "hctim.failmode[{profile_fit_index}]"
    init: True

  - name: "ProfileFitStatus"
    expression: "prfc.failmode[{profile_fit_index}]"
    init: True

  - name: "GeometryFitQuality"
    expression: "hctim.mchi2[{profile_fit_index}] / (prfc.nbin[{profile_fit_index}] - 2)"
    init: True

  - name: "ProfileFitQuality"
    expression: "prfc.chi2[{profile_fit_index}] / prfc.ndf[{profile_fit_index}]"
    init: True

  - name: "HitSDsXXYY"
    expression: "tlfptn.xxyy"
    init: True

  - name: "HitSDsCLF"
    expression: "tlfptn.xyzclf"
    init: True



#  - name: "BorderDistance"
#    expression: "TLUTI_DETECTORS::get_sd_bdist(TAX4SD_208_N, eventVars.sdcorex, eventVars.sdcorey);"
#    init: True

#  - name: "EyeID"
#    expression: "stpln.eyeid[{hit_sd_index}]"
#    init: False

# Event Selection Criteria
cuts:
  - "Xmax > Xlow"
  - "Xmax < Xhigh"
  - "LogEnergy >= 18.5"
  - "Zenith <= 65."
  - "Psi <= 145."
  - "ProfileFitStatus == 0"
  - "ProfileFitQuality <= 25"
  - "GeometryFitStatus == 0"
  - "GeometryFitQuality <= 15"

# Histogram parameters
hist_params:
  - name: "hXmax"
    title: "X_{max}"
    style: "histogram"
    column: "Xmax"
    bins: 20
    min: 300
    max: 1400
    x_title: "X_{max} [g/cm^{2}]"
    y_title: "Events"
    show_stats: True
    y_range_user: ~
    options: ~

  - name: "hXlow"
    title: "X_{low}"
    style: "histogram"
    column: "Xlow"
    bins: 18
    min: 0
    max: 900
    x_title: "X_{low} [g/cm^{2}]"
    y_title: "Events"
    show_stats: True
    y_range_user: ~
    options: ~

  - name: "hXhigh"
    title: "X_{high}"
    style: "histogram"
    column: "Xhigh"
    bins: 24
    min: 300
    max: 1500
    x_title: "X_{high} [g/cm^{2}]"
    y_title: "Events"
    show_stats: True
    y_range_user: ~
    options: ~

  - name: "hLogEnergy"
    title: "Energy"
    style: "histogram"
    column: "LogEnergy"
    bins: 14
    min: 18.0
    max: 21.5
    x_title: "log(E/eV)"
    y_title: "Events"
    show_stats: True
    y_range_user: ~
    options: ~

  - name: "hZenith"
    title: "Zenith"
    style: "histogram"
    column: "Zenith"
    bins: 9
    min: 0
    max: 90
    x_title: "Zenith [deg]"
    y_title: "Events"
    show_stats: True
    y_range_user: ~
    options: ""

  - name: "hPsi"
    title: "Psi"
    style: "histogram"
    column: "Psi"
    bins: 18
    min: 0
    max: 180
    x_title: "Psi [deg]"
    y_title: "Events"
    show_stats: True
    y_range_user: ~
    options: ""

  - name: "pXmaxEnergy"
    title: "#LTX_{max}#GT vs. Energy"
    style: "profile_plot"
    x_column: "LogEnergy"
    y_column: "Xmax"
    x_bins: 5
    y_bins: ~
    x_min: ~
    x_max: ~
    x_bin_edges:
      - 18.5
      - 18.75
      - 19.0
      - 19.25
      - 19.8
      - 20.3
    y_min: 400
    y_max: 1200
    x_title: "log(E/eV)"
    y_title: "#LTX_{max}#GT [g/cm^{2}]"
    show_stats: True
    x_range_user: ~
    y_range_user: 200, 1700
    options: ""

user_functions:
  - name: "Get Core XXYY"
    callable: "get_core_xxyy"
    args:
      - name: "column1"
        value: "HitSDsCLF"
      - name: "column2"
        value: "PulseArea"
#  - name: "Say Hello"
#    callable: "say_hello"