# txhybid_config.yaml

input_file: ${ALL_HYBRID}  # Path to the input ROOT file containing the data.
tree_name: "taTree"  # Name of the ROOT TTree to be analyzed.
output_dir: "/home/zane/software/new_analysis/txHybridDF/results"  # Directory to save the output results.
analysis_file: "/home/zane/software/new_analysis/txHybridDF/library/txHybrid_composition.py"  # Path to the analysis file.

# Detector settings
detector: "mdtax4"  # Name of the detector to be used in the analysis.
detectors:
  - name: "mdtax4"  # Name of the first detector.
    detector_id: "TAX4_MIDDLE_DRUM"
    site_id: 7  # Site ID of the first detector.
    profile: 6  # Profile fit index for the first detector.
  - name: "brtax4"
    detector_id: "TAX4_BLACK_ROCK"
    site_id: 8
    profile: 7

# New columns to define
new_columns:
  - name: "Xmax"  # Name of the new column.
    expression: "prfc.xm[{profile_fit_index}]"  # Expression to calculate the values of the new column.

  - name: "Xlow"
    expression: "prfc.dep[{profile_fit_index}][0]"

  - name: "Xhigh"
    expression: "prfc.dep[{profile_fit_index}][prfc.nbin[{profile_fit_index}]-1]"

  - name: "LogEnergy"
    expression: "18. + TMath::Log10(prfc.eng[{profile_fit_index}])"

  - name: "Zenith"
    expression: "TMath::RadToDeg()*hctim.mthe[{profile_fit_index}]"

  - name: "Psi"
    expression: "TMath::RadToDeg()*hctim.mpsi[{profile_fit_index}]"

  - name: "PulseArea"
    expression: "tlfptn.pulsa"

  - name: "TriggeredSDCount"
    expression: "tlfptn.nhits"

  - name: "GeometryFitStatus"
    expression: "hctim.failmode[{profile_fit_index}]"

  - name: "ProfileFitStatus"
    expression: "prfc.failmode[{profile_fit_index}]"

  - name: "GeometryFitQuality"
    expression: "hctim.mchi2[{profile_fit_index}] / (prfc.nbin[{profile_fit_index}] - 2)"

  - name: "ProfileFitQuality"
    expression: "prfc.chi2[{profile_fit_index}] / prfc.ndf[{profile_fit_index}]"

  - name: "HitSDsXXYY"
    expression: "tlfptn.xxyy"

  - name: "HitSDsCLF"
    expression: "tlfptn.xyzclf"

  - name: "Talex00HitSDsXXYY"
    expression: "talex00.xxyy"

  - name: "HybridCoreX"
    expression: "hctim.mcore[{profile_fit_index}][0]"

  - name: "HybridCoreY"
    expression: "hctim.mcore[{profile_fit_index}][1]"

# Event Selection Criteria
cuts:
  - "Xmax > Xlow"
  - "Xmax < Xhigh"
  - "LogEnergy >= 18.5"
  - "Zenith <= 65."
  - "Psi <= 145."
  - "ProfileFitStatus == 0"
  - "ProfileFitQuality <= 25"
  - "GeometryFitStatus == 0"
  - "GeometryFitQuality <= 15"
#  - "CoreProximity/1000 <= 5"

# Histogram parameters
hist_params:
  - name: "hXmax"  # Name of the histogram.
    title: "X_{max}"  # Title of the histogram.
    style: "histogram"  # Style of the plot (histogram).
    column: "Xmax"  # Column to be plotted.
    bins: 20  # Number of bins in the histogram.
    min: 300  # Minimum value of the histogram.
    max: 1400  # Maximum value of the histogram.
    x_title: "X_{max} [g/cm^{2}]"  # X-axis title.
    y_title: "Events"  # Y-axis title.
    show_stats: True  # Display statistics box on the plot.
    options: ~  # Additional options for the histogram.

  - name: "hXlow"
    title: "X_{low}"
    style: "histogram"
    column: "Xlow"
    bins: 18
    min: 0
    max: 900
    x_title: "X_{low} [g/cm^{2}]"
    y_title: "Events"
    show_stats: True
    options: ~

  - name: "hXhigh"
    title: "X_{high}"
    style: "histogram"
    column: "Xhigh"
    bins: 24
    min: 300
    max: 1500
    x_title: "X_{high} [g/cm^{2}]"
    y_title: "Events"
    show_stats: True
    options: ~

  - name: "hLogEnergy"
    title: "Energy"
    style: "histogram"
    column: "LogEnergy"
    bins: 14
    min: 18.0
    max: 21.5
    x_title: "log(E/eV)"
    y_title: "Events"
    show_stats: True
    options: ~

  - name: "hZenith"
    title: "Zenith"
    style: "histogram"
    column: "Zenith"
    bins: 9
    min: 0
    max: 90
    x_title: "Zenith [deg]"
    y_title: "Events"
    show_stats: True
    options: ~

  - name: "hPsi"
    title: "Psi"
    style: "histogram"
    column: "Psi"
    bins: 18
    min: 0
    max: 180
    x_title: "Psi [deg]"
    y_title: "Events"
    show_stats: True
    options:  ~

  - name: "hCoreProximity"
    title: "Core Proximity"
    style: "histogram"
    column: "CoreProximity"
    bins: 50
    min: 0
    max: 100
    x_title: "Core Proximity [km]"
    y_title: "Events"
    show_stats: True
    options: ~

  - name: "pXmaxEnergy"  # Name of the profile plot.
    title: "#LTX_{max}#GT vs. Energy"  # Title of the profile plot.
    style: "profile_plot"  # Style of the plot (profile plot).
    x_column: "LogEnergy"  # X-axis column.
    y_column: "Xmax"  # Y-axis column.
    x_bins: 5  # Number of bins in the x-axis.
    y_bins: ~  # Number of bins in the y-axis.
    x_min: ~  # Minimum value of the x-axis.
    x_max: ~  # Maximum value of the x-axis.
    x_bin_edges:  # List of bin edges for the x-axis.
      - 18.5
      - 18.75
      - 19.0
      - 19.25
      - 19.8
      - 20.3
    y_min: 400  # Minimum value of the y-axis.
    y_max: 1200  # Maximum value of the y-axis.
    x_title: "log(E/eV)"  # X-axis title.
    y_title: "#LTX_{max}#GT [g/cm^{2}]"  # Y-axis title.
    show_stats: True  # Display statistics box on the plot.
    options: ""  # Additional options for the profile plot.

user_functions:
  - new_column: "PulseAreaMean"
    callable: "meanVectorVector"
    language: "C++"
    args:
      - value: "PulseArea"

  - new_column: "HotSDSignal"
    callable: "findMaxInRVec"
    language: "C++"
    args:
      - value: "PulseAreaMean"

  - new_column: "HotSDIndex"
    callable: "findHotSDIndex"
    language: "C++"
    args:
      - value: "PulseAreaMean"

  - new_column: "FD_CLF_X"
    callable: "getFD_CLF"
    language: "C++"
    args:
      - value: "PulseAreaMean"

  - new_column: "HotSD_CLF"
    callable: ~
    language: ~
    args:
      - value: "HitSDsCLF"
      - value: "HotSDIndex"

  - new_column: "HotSD_CLF_X"
    callable: ~
    language: ~
    args:
      - value: "HotSD_CLF"
      - value: "0"

  - new_column: "HotSD_CLF_Y"
    callable: ~
    language: ~
    args:
      - value: "HotSD_CLF"
      - value: "1"

  - new_column: "HotSDxxyy"
    callable: ~
    language: ~
    args:
      - value: "HitSDsXXYY"
      - value: "HotSDIndex"

  - new_column: "CoreProximity"
    callable: "coreProximity"
    language: "C++"
    args:
      - value: "HybridCoreX"
      - value: "HybridCoreY"
      - value: "HotSD_CLF_X"
      - value: "HotSD_CLF_Y"
